### ISSUE TITLE
Missing dependencies: Cython, torchvision, PyQt5

### ISSUE THREAD

**Issue by lmmx** [hkchengrex/MiVOS#1]
In addition to the dependencies you mention,

- installing `davisinteractive` raised a warning about not having Cython but did succeed, however the code in `fbrs/utils/cython` obviously does not run.
- to run the interactive GUI required `PyQt5`, you may want to provide that in the list of requirements (it is not installed with `davisinteractive` for me).
- also got an error at runtime about missing `torchvision`

The working setup for a conda environment I used was

```sh
conda create -n mivos
conda activate mivos
conda install -y "cudatoolkit<11.2" -c conda-forge # 11.1.1
conda install -y pytorch torchvision -c pytorch # python 3.8.8 torch 1.8.0 torchvision 0.9.0
pip install davisinteractive progressbar2 opencv-python networkx gitpython gdown Cython
```

With this, the model runs for me (Ubuntu 20.04). Thought I should leave a note here so you can amend the README if you agree or at least help others.

By the way, very nicely packaged, all models should follow your example of `download_models.py` using gdown :smiley:

**Comment by hkchengrex** [comment]
Ah right...
I did not actually rebuild my environment to test the dependencies so I missed a few...

Thanks for the note! I will update the README in a bit.

**Comment by hkchengrex** [comment]
Fixed. Thanks again!
