### ISSUE TITLE
Processing on long video with high resolution

### ISSUE THREAD

**Issue by devidlatkin** [hkchengrex/MiVOS#12]
Hello!
Thank you for the amazing framework!

I have an issue while processing on long video with high resolution. I ran out of GPU memory.
As I understand, mivos tries to upload all images directly to GPU and if the video is too long or in high-resolution mivos can't handle such cases.
Is there is a way to fix this issue? Maybe modify code to work with data chunks?

Thank you in advance!

**Comment by hkchengrex** [comment]
That is correct. Perhaps you can try a different memory profile (e.g. 2): https://github.com/hkchengrex/MiVOS/blob/3d92044ee01432fa2672aa996ead57b07bace85b/interactive_gui.py#L990

I think it will still struggle if the video is really high-resolution and long... You can also increase `mem_freq`: https://github.com/hkchengrex/MiVOS/blob/3d92044ee01432fa2672aa996ead57b07bace85b/interactive_gui.py#L989

**Comment by devidlatkin** [comment]
Yeah, it works on CPU (--mem_profile 2) with my video but it takes a lot of time to propagate so it is almost impossible to annotate in real-time =(
It can work on GPU only if I use small chunks of 30 frames but it is really inconvenient to annotate the whole video by such small chunks...

I'm thinking about modifying interactive_gui.py to do propagation by chunks inside the framework. Is it possible to implement such logic? Does it violate some method restrictions?

**Comment by hkchengrex** [comment]
With `mem_profile=2` the algorithm still runs on the GPU. There are just a lot more CPU-to-GPU communications (images are stored on CPU, send to GPU for encoding and propagation, and the results are sent back to CPU) which are still unavoidable even if you do them in chunks... You can perhaps try [half precision](https://pytorch.org/docs/stable/amp.html).

Doing them in chunks does have the benefit of batching the CPU-GPU-CPU transfer so it might still be worth doing. The performance would not be the same, but you can try to implement a behavior where the algorithm discards most frames (except maybe last 5 for memory features) after 30 frames and loads the next 30 frames into the GPU for propagation and so on.

**Comment by devidlatkin** [comment]
Ok, got it.
Thank you!
