### ISSUE TITLE
About GUI tool.

### ISSUE THREAD

**Issue by Limingxing00** [hkchengrex/MiVOS#13]
Hi,  

It is awkward that our server hasn't support GUI. Do you know any solution?  

Thanks!

**Comment by hkchengrex** [comment]
You can still evaluate on DAVIS even if you don't have GUI... What else do you want to do?

**Comment by Limingxing00** [comment]
Well... although during training, this is really unnecessary. But the ultimate goal is to evalutate the effect of the model in a real user interaction environment.  Any way, thank you for the Reply！

**Comment by hkchengrex** [comment]
You can also use X11 forwarding to forward the GUI from the server to a user PC through SSH port. I haven't tried that for this particular program but I think it's possible.

Hope it helps.
