### ISSUE TITLE
A possible bug？

### ISSUE THREAD

**Issue by Limingxing00** [hkchengrex/MiVOS#14]
Hi,

In the [fusion_dataset.py ](https://github.com/hkchengrex/MiVOS/blob/210e76fc35edf9dcbe3f98a4bf4d74ce404ec79c/dataset/fusion_dataset.py), it may has a bug.

```python

# We need the second reference frame to be visible from the first
if not path.exists(path.join(video_path, first_ref, tar_obj, r+'.png')):
    continue
# We need the target object to exist
if path.exists(path.join(video_path, r, tar_obj, tar_frame)):
    src2_ref_options.append(r)

```

Should it be like this here?  Because ```tar_frame``` is a number like "00001".
```python
if path.exists(path.join(video_path, r, tar_obj, tar_frame+'.png')):
````

**Comment by hkchengrex** [comment]
I must admit that the naming is not exactly clear... Sorry about that

`tar_frame` is the file name while `tar_frame_int` is the integer.

https://github.com/hkchengrex/MiVOS/blob/210e76fc35edf9dcbe3f98a4bf4d74ce404ec79c/dataset/fusion_dataset.py#L107

https://github.com/hkchengrex/MiVOS/blob/210e76fc35edf9dcbe3f98a4bf4d74ce404ec79c/dataset/fusion_dataset.py#L109

**Comment by Limingxing00** [comment]
Thank you. It is my problem...
