### ISSUE TITLE
404 ERROR when downloading static dataset

### ISSUE THREAD

**Issue by JerryX1110** [hkchengrex/MiVOS#15]
When I downloaded the static image dataset from https://drive.google.com/uc?id=1wujq3hcldn-z1t4csuhjez9bvdb9ykld, I got a 404 ERROR.

**Comment by hkchengrex** [comment]
The link should be https://drive.google.com/uc?id=1wUJq3HcLdN-z1t4CsUhjeZ9BVDb9YKLd?
Cases matter.

**Comment by JerryX1110** [comment]
Problem solved, Thanks!

**Comment by JerryX1110** [comment]
The same problem occurred when downloading DAVIS dataset with the 'download_datasets.py' script. Maybe you need to change permission over 'Anyone with the link'?
