### ISSUE TITLE
Is that possible this work in  real-time case

### ISSUE THREAD

**Issue by mathmax12** [hkchengrex/MiVOS#17]
Hi 
Thanks for sharing the amazing work.
Does the work support real-time case?
If not what change do you recommend for that?
Thanks.

**Comment by hkchengrex** [comment]
Can you elaborate on what properties do your real-time case needs? (speed/online/long sequences?)

**Comment by mathmax12** [comment]
For example, processing the video stream from a camera in real-time 30FPS.

**Comment by hkchengrex** [comment]
Speed-wise, the current model can handle it with [PyTorch's AMP](https://pytorch.org/docs/stable/amp.html) enabled in the single object setting. But then there are also considerations regarding inputs (this is after all an interactive method) and memory (feature bank growing over time as in STM).

**Comment by mathmax12** [comment]
I see.
Thanks for that.
