### ISSUE TITLE
A consultation on your used GPU

### ISSUE THREAD

**Issue by Starboy-at-earth** [hkchengrex/MiVOS#2]
Dear author:
Could you please tell me if two 2080Ti are enough for reproducing your results? Thank you in advance!!! PS. If the answer is yes, could you please tell how much time I need to spend on it?

**Comment by hkchengrex** [comment]
Yes, they are enough.
I need around two weeks to train everything from scratch (propagation, scribble to mask, and fusion) with two 1080Tis. With the faster 2080Tis, it is probably going to take around 10 days.
