### ISSUE TITLE
Process killed

### ISSUE THREAD

**Issue by zdhernandez** [hkchengrex/MiVOS#22]
I tried the MIVOS + STCN on  a 1.5 minute 4k video that was down sampled to 480p and the program crashed.

What are the steps to reformat/sample a 4k video to make it work for this tool?

Also can this tool run on multiple GPUs?

**Comment by hkchengrex** [comment]
What was the error?

**Comment by zdhernandez** [comment]
> What was the error?
@hkchengrex 
attached pictures
![Screenshot from 2021-12-02 15-24-33](https://user-images.githubusercontent.com/8461519/144518951-f2c90ae9-7307-4559-bcf3-29e769c3aa00.png)
![Screenshot from 2021-12-02 15-26-55](https://user-images.githubusercontent.com/8461519/144519036-b3f85a24-512e-4b0c-85e4-4e441e2f3523.png)
![Screenshot from 2021-12-02 15-27-42](https://user-images.githubusercontent.com/8461519/144519105-af78144d-7563-472b-8629-c255294da0b3.png)

**Comment by hkchengrex** [comment]
Can you try `--mem_profile 2`?

**Comment by hkchengrex** [comment]
There are also a lot of frames so maybe you need to set `--mem_freq` higher, e.g., 30.

**Comment by zdhernandez** [comment]
> Can you try `--mem_profile 2`?

@hkchengrex seems to work.  Do you think you have memory leaks ? Because the video I'm trying to use is only 34MB. 
I see what it is doing now in:
```
class InferenceCore:
    """
    images - leave them in original dimension (unpadded), but do normalize them. 
            Should be CPU tensors of shape B*T*3*H*W
            
    mem_profile - How extravagant I can use the GPU memory. 
                Usually more memory -> faster speed but I have not drawn the exact relation
                0 - Use the most memory
                1 - Intermediate, larger buffer 
                2 - Intermediate, small buffer 
                3 - Use the minimal amount of GPU memory
                Note that *none* of the above options will affect the accuracy
                This is a space-time tradeoff, not a space-performance one

    mem_freq - Period at which new memory are put in the bank
                Higher number -> less memory usage
                Unlike the last option, this *is* a space-performance tradeoff
    """
```

![Screenshot from 2021-12-02 15-32-26](https://user-images.githubusercontent.com/8461519/144519485-8ea5033d-82a0-469c-85ce-d4780978e067.png)

**Comment by hkchengrex** [comment]
34MB is the size after compression. Raw pixels occupy much more space. The model in this branch https://github.com/hkchengrex/MiVOS/tree/MiVOS-STCN will perform better/use somewhat less memory I believe.

**Comment by zdhernandez** [comment]
> 34MB is the size after compression. Raw pixels occupy much more space. The model in this branch https://github.com/hkchengrex/MiVOS/tree/MiVOS-STCN will perform better/use somewhat less memory I believe.

@hkchengrex that's the branch I'm using. So what do we need to do to control the memory. I see the YouTube videos which are long and high resolution. What's different there ? How was the input of a large resolution video adjusted to the tool without you know crashing the GPU memory or causing memory issues ? Was a much more powerful hardware used ? or multiple GPUs ?

**Comment by hkchengrex** [comment]
None of the youtube videos are that long (<500 frames). We just downsample high-res video to 480p (probably like what you did).
We used a 2080Ti (11GB) and that should be sufficient for all the examples shown.

For your setting, I would suggest a higher `mem_freq` and use 480p videos to generate the masks (upsample afterward).

**Comment by zdhernandez** [comment]
> None of the youtube videos that we show are that long (<500 frames). We just downsample high-res video to 480p (probably like what you did). We used a 2080Ti (11GB) and that should be sufficient for all the examples shown.
> 
> For your setting, I would suggest a higher `mem_freq` and use 480p videos to generate the masks (upsample afterward).

@hkchengrex I see. So a higher 'mem_freq' with video down-sampled for MIVOS + STCN processing and then once finished the masks are up-sampled as post-processing to match the dimension of the original 1080 or 4K video. Does that sound right ?

**Comment by hkchengrex** [comment]
Yes.

**Comment by zdhernandez** [comment]
> Yes.

@hkchengrex  got it! Thank you very much!
