### ISSUE TITLE
-- images mem_profile 2 | RuntimeError: All input tensors must be on the same device. Received cpu and cuda:0

### ISSUE THREAD

**Issue by zdhernandez** [hkchengrex/MiVOS#23]
To replicate:
- create folder with only one image
- with these settings run: `python interactive_gui.py  --mem_profile 2 --images ./example/test_folder/`
- select the "click" radio button
- click on the image to create mask
- select "scribble" radio button
- "scribble" an area in the picture
- runtime error is thrown
![Screenshot from 2021-12-03 22-06-00](https://user-images.githubusercontent.com/8461519/144699591-0097c043-96fe-4c5e-83c1-0cbbe05ff023.png)

**Comment by hkchengrex** [comment]
Thanks for reporting. It should be fixed now.

**Comment by zdhernandez** [comment]
@hkchengrex  The latest version is not working. This is what I get when I try to run it.
![Screenshot from 2021-12-05 11-29-16](https://user-images.githubusercontent.com/8461519/144760757-c1408aa3-ce70-40e6-8c43-8cbedd288e95.png)

**Comment by hkchengrex** [comment]
hmm it is an unused import. Try again?

**Comment by zdhernandez** [comment]
@hkchengrex  this is what I got now when I tried to run it.
![Screenshot from 2021-12-05 12-05-58](https://user-images.githubusercontent.com/8461519/144762110-5b3a1194-a27f-4aff-b404-1ebae2ee5d3c.png)

**Comment by hkchengrex** [comment]
This means you have to download the model files as mentioned in the readme
