### ISSUE TITLE
Overlay and Mask files not equal to size of original input image.

### ISSUE THREAD

**Issue by zdhernandez** [hkchengrex/MiVOS#24]
@hkchengrex 
Doing one image larger than 1k resolution in one folder with command:
`python interactive_gui.py  --mem_profile 2 --images ./example/test_folder/
`

- clicking on an object to produce the mask
- click "save" to save the overlay and masks
- Both overlay and mask files are reduced to a fix resolution of: width: 480px, height: 640px

Q. Can we keep the size of the output files to be equal to the input size of the original image?
Q. Can we add a flag to use either current behavior or preserve the resolution of the input image ?

**Comment by hkchengrex** [comment]
The resizing behavior is implemented here: https://github.com/hkchengrex/MiVOS/blob/44f2caef7f943a04141ee533811cb9b726e89750/interactive_gui.py#L1008-L1011

(Pass None in place of 480 to disable resizing)

**Comment by hkchengrex** [comment]
I just spotted a bug with `mem_profile=2`. I will fix it in a bit.

**Comment by zdhernandez** [comment]
@hkchengrex  Thanks for showing me the line of code doing that. I can alter the local source code and pass None but then that goes away next time you update your branch. IS this something you could add as a flag to the "parser" ?  something like:
`--resize, default=0, type=int, help='0 - Faster interaction resizes frames to 480px; 1 - preserves original frame input size'`

```
 if args.images is not None: 
     if args.resize:
           images = load_images(args.images, None) 
     else:
           images = load_images(args.images, 480) 
 elif args.video is not None: 
     if args.resize:
           images = load_video(args.video, None) 
     else:
           images = load_video(args.video, 480) 
```

**Comment by hkchengrex** [comment]
It is fixed now. I have added a `--resolution` flag. Pass `-1` to it to keep the original shape.
