### ISSUE TITLE
"prob1" bug in interactive_gui.on_undo()

### ISSUE THREAD

**Issue by bananajoe182** [hkchengrex/MiVOS#28]
Hi,

I think there is a typing error in interactive_gui.py lines 616 and 626. 
` self.interacted_mask = self.processor.prob1[:, self.cursur].clone()` 

it should be "self.processor.prob" not "prob1"

When one tries to undo the first interaction on a frame it throws an error:

` line 626, in on_undo
    self.interacted_mask = self.processor.prob1[:, self.main_gui.cursor].clone()
AttributeError: 'InferenceCore' object has no attribute 'prob1'`

**Comment by hkchengrex** [comment]
Thanks! fixed.
