### ISSUE TITLE
ratio = self.progress_num/self.progress_max  ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by tholmb** [hkchengrex/MiVOS#29]
Thanks for sharing this great tool/project! Basically everything is working like a charm but if I make too many propagation steps while running interactive_gui.py I will face following error message and all modifications are gone (I would say that on average it happens after 20-30 propagation steps).

    [A: 3798.09, U: 3057.62]: Propagation started.
    [A: 3799.22, U: 3057.62]: Propagation finished!
    [A: 3804.20, U: 3062.58]: Interaction Scribble at frame 579.
    [A: 3805.13, U: 3063.38]: Interaction Scribble at frame 579.
    [A: 3806.62, U: 3064.74]: Interaction Scribble at frame 579.
    [A: 3811.83, U: 3069.87]: Propagation started.
    Traceback (most recent call last):
      File "interactive_gui.py", line 550, in on_run
        self.current_mask = self.processor.interact(self.interacted_mask, self.cursur, 
      File "/home/user/projects/MiVOS/inference_core.py", line 252, in interact
        total_cb(total_num)
      File "interactive_gui.py", line 540, in progress_total_cb
        self.progress_step_cb()
      File "interactive_gui.py", line 532, in progress_step_cb
        ratio = self.progress_num/self.progress_max
    ZeroDivisionError: division by zero

It looks like that for some reason self.progress_max or total_num in inference_core.py gets value 0. Can I avoid this error by checking with: if self.progress_max == 0 -> self.progress_max = 1 or something similar. Do you have a clue what causes the error?

**Comment by hkchengrex** [comment]
Yeah, it is probably a bug. I am guessing that it is caused by an interaction right next to another interacted frame. I will check later.

**Comment by hkchengrex** [comment]
Can be reproduced by: interact with frame 1 -> interact with frame 3 -> interact with frame 2. 

Thanks for reporting. Fixed.
