### ISSUE TITLE
Which line of your code is to achieve Memory Read with Top-k Filtering？

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/MiVOS#3]
Hi, thanks for your great work. Which line of your code is to achieve Memory Read with Top-k Filtering？

**Comment by longmalongma** [comment]
> Hi, thanks for your great work. Which line of your code is to achieve Memory Read with Top-k Filtering？

Your code is used for Interactive Video Object Segmentation. If we use your code to do semi-supervised vos, what changes need to be made?

**Comment by hkchengrex** [comment]
1. This line: https://github.com/hkchengrex/MiVOS/blob/b1992e6a2ecab84ff1b61f896e501cb357ee7b3d/model/propagation/prop_net.py#L54
2. You should use [Mask-Propagation](https://github.com/hkchengrex/Mask-Propagation). I have them labelled on the first table in the readme!

**Comment by longmalongma** [comment]
> 1. This line: https://github.com/hkchengrex/MiVOS/blob/b1992e6a2ecab84ff1b61f896e501cb357ee7b3d/model/propagation/prop_net.py#L54
> 2. You should use [Mask-Propagation](https://github.com/hkchengrex/Mask-Propagation). I have them labeled in the first table of the readme!

Ok, I see it, thanks for your reply.
