### ISSUE TITLE
RuntimeError: "slow_conv_dilated<>" not implemented for 'BFloat16'(example.mp4)

### ISSUE THREAD

**Issue by xwhkkk** [hkchengrex/MiVOS#31]
Hello!  I followed the instructions of Quickstart with these settings:  _python interactive_gui.py --video .\example\example.mp4_
As I don't have a GPU, I change the map location to 'CPU'. When I select the "click" radio button and click on the object to create the mask, a runtime error is thrown.
![image](https://user-images.githubusercontent.com/50388024/154631033-1cb959ea-ade6-45ca-a8c9-522502ce9f47.png)
Could you give me some suggestions? Looking forward to your reply.

**Comment by hkchengrex** [comment]
Try `--no_amp`.
You need to change more than one line/file of code though, using CPU would be very slow so I assumed GPU in a lot of code.

**Comment by xwhkkk** [comment]
> Try `--no_amp`. You need to change more than one line/file of code though, using CPU would be very slow so I assumed GPU in a lot of code.

Thank you! It works with `--no_amp`,  but the runtime error still exists if I use other images or videos.

**Comment by hkchengrex** [comment]
Same error? What's different about the new images/videos?

**Comment by xwhkkk** [comment]
> Same error? What's different about the new images/videos?

Yes, the same error (using CPU). The images I used are 384*384 in jpg format.

**Comment by hkchengrex** [comment]
Everything works for the example video but nothing works for the new images? There is little difference between processing images/videos. Can you give more details?

**Comment by xwhkkk** [comment]
> Everything works for the example video but nothing works for the new images? There is little difference between processing images/videos. Can you give more details?

I tested the "example.mp4" and 384*384  images with  `--video` and  `--images` respectively. Both of them give the same run error with using CPU, but it works fine with  `--no_amp`. The same video and images work fine with using GPU.
