### ISSUE TITLE
Question of the val.txt used in eval_interactive_davis.py

### ISSUE THREAD

**Issue by xwhkkk** [hkchengrex/MiVOS#35]
Hello! I reduced the sequence in the val.txt of DAVIS2017. But it gave the KeyError below:
![davis_test](https://user-images.githubusercontent.com/50388024/159712873-fb84e413-9f1f-43bb-9414-13aa5f244d31.JPG)
Could you give me some suggestions?

**Comment by hkchengrex** [comment]
`DavisInteractiveSession` is probably ignoring val.txt. That is internal to DAVIS. You can probably add something like 
```python
if sequence not in ['bike-packing', '...', ...]:
    continue
```

**Comment by xwhkkk** [comment]
Thanks for your reply! It works well
