### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PropagationNetwork

### ISSUE THREAD

**Issue by xwhkkk** [hkchengrex/MiVOS#36]
Hello!  I replaced the propagation network  propagation_model.pth with the stcn.pth in  `interactive_gui.py`. But it came with a running error.
![stcn_error](https://user-images.githubusercontent.com/50388024/159922288-e66a7638-bed2-4448-b442-79cc7e5e38cf.JPG)

Could you give me some suggestions?

**Comment by hkchengrex** [comment]
Go to the MiVOS-STCN branch.

**Comment by xwhkkk** [comment]
Thank you !  I solved this problem .
