### ISSUE TITLE
在scribble的时候上一次的mask数据保存在哪里

### ISSUE THREAD

**Issue by lixiong4788** [hkchengrex/MiVOS#37]
您好，问一下：
    当我们从click模式切换到scribble的时候，click所生成的mask数据保存在哪里了呢？

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/MiVOS/blob/7fe0d988e64ce1363f3780840c74c1fd6cb827f4/interactive_gui.py#L899-L913
