### ISSUE TITLE
Some problem when train Fusion

### ISSUE THREAD

**Issue by 1173161983** [hkchengrex/MiVOS#39]
Hello, I encountered some problems when retraining the **fusion** model. Some key parameter guidelines for training fusion are not given in the code warehouse. Can you provide it?
Specifically as follows:
(1) generate_fusion.py: parameter "separation" not given

Can you provide the relevant parameter descriptions of fusion training and the instructions to run so that I can reproduce the results of your paper?

and when I try to train（python train.py）,I meet some code mistake in fusion_dataset.py：
（1）are there some mistake When you assign a value to self.vid_to_instance？ and It will return error at：
self.videos = [v for v in self.videos if v in self.vid_to_instance]（line 60 in fusion_datast.py）

**Comment by hkchengrex** [comment]
We provided the pre-computed fusion data for download. The names of the folders should reflect the parameters I used. Like "sep30" means separation=30, `m20` means mem_freq=20. I also haven't generated the fusion data for the entire dataset.

**Comment by hkchengrex** [comment]
My current L60 in fusion_dataset is different. I did a brief scan and couldn't find the problem.

**Comment by 1173161983** [comment]
the problem when train fusion(train.py),is :

**Comment by hkchengrex** [comment]
So your `self.vid_to_instance` is empty? It doesn't happen to me.

**Comment by 1173161983** [comment]
Really? I have to change the code (fusion_dataset.py, line 50) to :
(fusion_dataset.py, line 50)
for folder in fuse_list:
    # folder_path = path.join(self.fd_root, folder)
    # video_list = sorted(os.listdir(folder_path))    # ['00000', '00020', '00040', '00060']
    # print("video list", video_list)
    # video level - different videos
    # for vid in video_list:
    video_path = path.join(self.fd_root, folder) #, vid)
    self.vid_to_instance[folder].append(video_path)
    total_fuse_vid += 1

so can I train the fusion model.  
meybe  the code at github is different from your's ?

**Comment by 1173161983** [comment]
In my code the data in self.video is different from self.vid_to_instance.

so it comes error at  fusion_dataset.py :
self.videos = [v for v in self.videos if v in self.vid_to_instance]

**Comment by 1173161983** [comment]
are you use YV when train the fusion model? how many dataset you used to trian fusion model?

**Comment by 1173161983** [comment]
hi, I have a new question:

can you give me the code that used to eval YTB dataset? (multi reference)

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/Mask-Propagation

**Comment by 1173161983** [comment]
so, if I use the fusion_data  you provide，I can get the result the same as paper?
