### ISSUE TITLE
How to generate "Fusion data"

### ISSUE THREAD

**Issue by UndecidedBoy** [hkchengrex/MiVOS#4]
Hello,

Great work and GitHub repositories!
I was curious regarding the **Fusion data** generation, could you clarify the arguments (i.e. `--separation`,`--range`,..) you used for generating the data with `generate_fusion.py`?
https://github.com/hkchengrex/MiVOS/blob/b1992e6a2ecab84ff1b61f896e501cb357ee7b3d/generate_fusion.py#L24-L36

Also, it seems that a link is missing for downloading the pre-generated fusion data in the **README.md**

Best!

**Comment by hkchengrex** [comment]
Thanks for reminding me. I have fixed the links.

DAVIS train set (range does not matter):
Set 1 - separation: 5, memory freq: 10
Set 2 - separation: 5, memory freq: 20
Set 3 - separation: 5, memory freq: 30

BL30K:
Set 1 - separation: 30, memory freq: 20, range: 90, start 0, end 5000
Set 2 - separation: 30, memory freq: 20, range: 90, start 5000, end 10000

I generated a few sets for each dataset to increase diversity. These parameters can also be inferred from the names of the folders.
