### ISSUE TITLE
static dataset in download_dataset.py

### ISSUE THREAD

**Issue by 1173161983** [hkchengrex/MiVOS#41]
I note that there are a static dataset in download_dataset.py
so, where is this static dataset used?

and in readme.md, you say, you use BL30K to train fusion model, and the BL30K is very large(600G), so ,you use 600 G dataset to
pretrain fusion model?

**Comment by hkchengrex** [comment]
1. For pretraining. See our paper or the STM paper.
2. A subset of it. You can download our pre-generated fusion_data to check but I don't think it matters too much. The fusion module is pretty easy to train.

**Comment by 1173161983** [comment]
thanks..
so, you use BL30K_a 0~1000 video to pretrain fusion model?

**Comment by hkchengrex** [comment]
I couldn't recall but I used fusion_data. I don't have that on my computer right now but if that's what you saw it should be correct.
