### ISSUE TITLE
Training for propagate module with 1 GPU

### ISSUE THREAD

**Issue by tony71200** [hkchengrex/MiVOS#43]
Hi.
I read your paper about MiVOS, and I think it is so great. 
I am training this model, but I have a problem training in 1 GPU.
Could you please show me the command line to train a propagation model with 1 GPU?
Thank you very much, and look forward to hearing from you.

**Comment by hkchengrex** [comment]
`python -m torch.distributed.launch --master_port 23453 --nproc_per_node=1 train.py --id someid --stage 0 --batch_size 24`
See the readme for loading the stage 0 model to train stage 1.
