### ISSUE TITLE
How to change label color

### ISSUE THREAD

**Issue by cpfy** [hkchengrex/MiVOS#45]
Hi, I found that the label generated is red mask（**R:128,G:0,B:0**）and a black( **R:0,G:0,B:0** ) background in default.

How do I set the color of the label with custom RGB parameters? 

Thank u!

**Comment by hkchengrex** [comment]
You can read them with PIL and apply your own palette.

**Comment by cpfy** [comment]
sorry i'm new to PIL.  :(

can you show an example of how to modify it? I want to change the mask to white and I found the following code in `imteractive_gui.py`

```python
# Save mask
mask = Image.fromarray(self.current_mask[i]).convert('P')
mask.putpalette(palette)
mask.save(os.path.join(mask_dir, '{:05d}.png'.format(i)))
```
