### ISSUE TITLE
Propagation failed

### ISSUE THREAD

**Issue by AppleMax1992** [hkchengrex/MiVOS#48]
Dear author, it is a great work.
However, when I use the interaction_gui for mask propagation after I manually scribble the mask for some frames and then click the propagation button, why did the mask propagate not generate a mask for frame normally?

**Comment by hkchengrex** [comment]
Label a frame -> propagate. You cannot propagate from multiple frames at once.

**Comment by AppleMax1992** [comment]
Thank you for your attention.
I have followed your suggestion and I only label the first frame of my test video using the "free scribble", then I click the propagation button. The program can run smoothly and there is no error in the log. However, the propagation mask didn't generate automatically for the following frames. Is there anything I did wrong?

**Comment by AppleMax1992** [comment]
Here is the labeled the first frame, and the propagation is processing.
![image](https://github.com/hkchengrex/MiVOS/assets/77500295/10aad3b7-7bfe-44e8-84da-bb26f932deff)
But when the propagation finished. the second frame can't have the generated mask as shown in the following image.
![image](https://github.com/hkchengrex/MiVOS/assets/77500295/e9f4021a-3c89-41bf-9535-ca324afa7376)
And this happens on all subsequent frames, none of them are masking automatically.

**Comment by hkchengrex** [comment]
Hmm... that should not happen. Does it work when you use other types of interactions?

P.S. This project is a bit old and most people use this now: https://github.com/hkchengrex/XMem

**Comment by AppleMax1992** [comment]
Yes, Xmen is a better project, faster, and less GPU intensive. But I have the same problem with the Xmen project.
I labeled two objects and run the forward propagation. 
![image](https://github.com/hkchengrex/MiVOS/assets/77500295/aaf248c2-e29c-4bd1-91b9-7c6c38720e68)
But yet, there is no mask generated for the subsequent frames.
![image](https://github.com/hkchengrex/MiVOS/assets/77500295/0650d089-9237-4be1-a9d5-486970ece0c6)
So I went back to your previous version as MIVOS, but my problem still exists.
However, I haven't tried other types of interaction, let me try them and give you feedback, thanks

**Comment by hkchengrex** [comment]
It might be an instantiation of https://github.com/hkchengrex/XMem/issues/41

**Comment by AppleMax1992** [comment]
Great answer, I think that should be the problem, let me first.

**Comment by AppleMax1992** [comment]
I reinstall PyTorch 1.11 and CUDA 10.2. It finally works smoothly. Then this issue should be closed.
Many thanks for your attention and suggestions.

**Comment by hkchengrex** [comment]
Glad it worked. It still seems peculiar to me that this would happen...
