### ISSUE TITLE
How we test without interactive_gui ?

### ISSUE THREAD

**Issue by miaoYuanyuan** [hkchengrex/MiVOS#5]
when the image number too larger, the GUI will Collapse and out of memory. I want to use it without GUI

**Comment by hkchengrex** [comment]
Test it under which setting?

**Comment by miaoYuanyuan** [comment]
only with command on servers without desktop,  input frames and pre_mask processed already .

**Comment by hkchengrex** [comment]
What is `pre_mask`? First frame mask or mask of several frames?

**Comment by miaoYuanyuan** [comment]
first frame mask.
Thank you , I know how to solve it .

**Comment by hkchengrex** [comment]
Then it is a semi-supervised setting. Use [Mask-Propagation](https://github.com/hkchengrex/Mask-Propagation).

**Comment by zdhernandez** [comment]
> Collapse

I'm having the same problem. Why would it crashed? I have plenty of memory. I get prices killed when trying to open the tool with a 1.5 minute long resampled video at 480p that was originally a 4k video.
