### ISSUE TITLE
attention heatmap

### ISSUE THREAD

**Issue by cjh8817676** [hkchengrex/MiVOS#50]
![image](https://github.com/hkchengrex/MiVOS/assets/49804319/45fb2479-f6d4-48b1-8a84-454ef0f73009)
I want to generate attention heatmaps just like memory frames in picture I post. Which part of the code should I use?

**Comment by hkchengrex** [comment]
This is probably not from our paper. Something related would be: https://github.com/hkchengrex/Mask-Propagation/blob/main/try_correspondence.py

**Comment by cjh8817676** [comment]
Thank's for your response.
In your paper, Section 3.3, Temporal Propagation, you mentioned "Following STM [7]," so I went to read that paper(https://arxiv.org/pdf/1904.00607.pdf). The image I posted is indeed from that paper. I wanted to gain a better understanding of how the attention mechanism operates within the propagation module, which is why I wanted to generate an attention heatmap. 
I will try to follow the suggestions you provided.
