### ISSUE TITLE
Fusion.pth has expired. Please update it，thanks

### ISSUE THREAD

**Issue by Corawill** [hkchengrex/MiVOS#53]
Hello, the google drive link of fusion.pth has expired. Could you please update it? Thank you so much

**Comment by hkchengrex** [comment]
Doesn't look expired on my end. Can you download it here https://github.com/hkchengrex/MiVOS/releases/tag/1.0 instead?

**Comment by hkchengrex** [comment]
DIrect link: https://github.com/hkchengrex/MiVOS/releases/download/1.0/fusion.pth

**Comment by Corawill** [comment]
Oh yes!! I got it, thank you for replying to me so quickly, you are so kind. Have a nice day!❤️
