### ISSUE TITLE
Download Dataset BL30K Error

### ISSUE THREAD

**Issue by dongho-Han** [hkchengrex/MiVOS#55]
Hello.
Thanks for the nice works!
I'm interested in working with VOS task, and your work is quite interesting for me.
Especially, i'm trying to test your work with dataset BL30K, but it can't be downloaded now both on  google drive and onedrive.
Could you check and update the links?

Thanks!

**Comment by hkchengrex** [comment]
What errors are you getting for Google Drive? It looks fine on my end.
I have refreshed the date for OneDrive.

**Comment by dongho-Han** [comment]
Thanks for the fast reply!
In my desktop, from now, I can download with browser.
However, when i try to use 'download_bl30k.py',
`gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1z9V5zxLOJLNt1Uj7RFqaP2FZWKzyXvVc

but Gdown can't. Please check connections and permissions.`

Could you check on this?
i'm using the STCN's download_bl30k.py code, but i think it wouldn't matter.

**Comment by hkchengrex** [comment]
Unfortunately that's a Google problem.
One way that I find useful is to 1) make a shortcut of the folder to your own Google Drive, and 2) use `rclone` to copy from your own Google Drive (would not count towards your storage limit).
