### ISSUE TITLE
I can not download BL30K 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/MiVOS#56]
When I execute this order: wget ckcpu1.cse.ust.hk:8080/MiVOS/BL30K_a.tar
![image](https://github.com/hkchengrex/MiVOS/assets/40291722/c1409c3c-7322-40d7-8770-b4cd4f7568a5)

**Comment by hkchengrex** [comment]
Unfortunately, it has been quite some time so the ckcpu link might not work anymore. I recommend the Google Drive + rclone pipeline here https://github.com/hkchengrex/MiVOS?tab=readme-ov-file#download

... 1) make a shortcut of the folder to your own Google Drive, and 2) use `rclone` to copy from your own Google Drive (would not count towards your storage limit)...

**Comment by longmalongma** [comment]
> Unfortunately, it has been quite some time so the ckcpu link might not work anymore. I recommend the Google Drive + rclone pipeline here https://github.com/hkchengrex/MiVOS?tab=readme-ov-file#download
> 
> ... 1) make a shortcut of the folder to your own Google Drive, and 2) use `rclone` to copy from your own Google Drive (would not count towards your storage limit)...



> Unfortunately, it has been quite some time so the ckcpu link might not work anymore. I recommend the Google Drive + rclone pipeline here https://github.com/hkchengrex/MiVOS?tab=readme-ov-file#download
> 
> ... 1) make a shortcut of the folder to your own Google Drive, and 2) use `rclone` to copy from your own Google Drive (would not count towards your storage limit)...

Thank you for your reply, but our local windows computer storage is not enough, how to directly download to the linux server.

**Comment by hkchengrex** [comment]
You can use `rclone` on Linux! I do this all the time :)
