### ISSUE TITLE
How can I generate video prediction results without GUI interface?

### ISSUE THREAD

**Issue by xmy0916** [hkchengrex/MiVOS#6]
Thank you for your work. How can I generate video prediction results without GUI interface? I want to test it on the server.

**Comment by hkchengrex** [comment]
Under which setting? DAVIS interactive or semi-supervised?

**Comment by hkchengrex** [comment]
Updated readme. Closed due to inactivity.

**Comment by Shivamshaiv** [comment]
Lets say i wanted to test a custom semi supervised video on the server without the GUI. How could I do it?

**Comment by hkchengrex** [comment]
For the semi-supervised setting go to [Mask Propagation](https://github.com/hkchengrex/Mask-Propagation).

1. The easiest way is to change your data into DAVIS/YouTubeVOS format, use `eval_davis.py` or `eval_youtube.py` and point the data directory to your data.
2. You can also change our the evaluation script and dataloader to fit your own data.
