### ISSUE TITLE
Modification on memory

### ISSUE THREAD

**Issue by vavenCV** [hkchengrex/MiVOS#8]
I'm testing and modifying the frequency at which the frames are put in memory "mem_freq" in inferencecore.py and how they are managed. 

I was wondering if any modification on how the frames (key and values) are arranged in memory is affected by training and if I needed to retrain the model on another mem_freq.

Also I'm experiencing with a sliding window memory (buffer), and was wondering if it could also be affected by training and if only modifying the code and running it on DAVIS val dataset without training was ok.

**Comment by hkchengrex** [comment]
I think you can do those without retraining and get a pretty good result.

**Comment by vavenCV** [comment]
Yeah I have done it and evaluated and got results, was just to know if I needed to retrain.

**Comment by hkchengrex** [comment]
Probably you can get better results but I am not sure by how much...
Like if you are increasing the memory frequency you might also want to increase the frame_skip in training.
And if you use a sliding window you might try similar things in training.
