### ISSUE TITLE
Has anyone met the following problem during the running of "interactive_gui.py"?

### ISSUE THREAD

**Issue by Starboy-at-earth** [hkchengrex/MiVOS#9]
Traceback (most recent call last):
  File "interactive_gui.py", line 23, in <module>
    from PyQt5.QtWidgets import (QWidget, QApplication, QMainWindow, QComboBox, QGridLayout, 
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/fg/anaconda3/envs/MiVOS/lib/python3.7/site-packages/PyQt5/QtWidgets.abi3.so)

**Comment by Starboy-at-earth** [comment]
@hkchengrex

**Comment by Starboy-at-earth** [comment]
pip install PyQt5
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: PyQt5 in /home/fg/anaconda3/envs/MiVOS/lib/python3.7/site-packages (5.15.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/fg/anaconda3/envs/MiVOS/lib/python3.7/site-packages (from PyQt5) (12.8.1)
Requirement already satisfied: PyQt5-Qt5>=5.15 in /home/fg/anaconda3/envs/MiVOS/lib/python3.7/site-packages (from PyQt5) (5.15.2)
######################################################
I have tried to reinstall it, but the prompt reminds me that I have had it in the environment.

**Comment by hkchengrex** [comment]
I have not encountered this problem before. Probably you have a system installed Qt (which is not the same as the one installed by pip) and python is not linking correctly. This might help: https://stackoverflow.com/questions/39129615/pyqt5-not-finding-installed-qt5-library

**Comment by Starboy-at-earth** [comment]
https://blog.csdn.net/jiguangfan/article/details/86488573. @hkchengrex Thank you very much!!!!
